# SPDX-License-Identifier: GPL-2.0-only WITH Linux-syscall-note

header-y += audio_compressed_formats.h
header-y += audio_effects.h
header-y += audio_slimslave.h
header-y += devdep_params.h
header-y += lsm_params.h
header-y += msmcal-hwdep.h
header-y += voice_params.h
header-y += wcd-dsp-glink.h
