# SPDX-License-Identifier: GPL-2.0-only

KDIR := $(TOP)/kernel_platform/msm-kernel
LINUXINCLUDE    += -I$(SYNC_FENCE_ROOT)sync_fence/include/

obj-m += sync_fence.o

sync_fence-y := src/qcom_sync_file.o

CDEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
